/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Isla.glb --types 
*/

import * as THREE from 'three'
type GLTFAction = THREE.AnimationClip;
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib';
import type { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Cubo: THREE.Mesh
    Isla: THREE.Mesh
    Agua: THREE.Mesh
    Roca_1: THREE.Mesh
    Roca_2: THREE.Mesh
    Roca_3: THREE.Mesh
    Arbol: THREE.Mesh
    Arbol001: THREE.Mesh
    Arbol002: THREE.Mesh
    Roca_2001: THREE.Mesh
    Roca_2002: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Isla(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/Isla.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cubo.geometry} material={materials['Material.001']} position={[4.868, 1.511, 6.965]} scale={0.597} />
      <mesh geometry={nodes.Isla.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Agua.geometry} material={materials['Material.004']} position={[9.859, 0.283, -0.003]} />
      <mesh geometry={nodes.Roca_1.geometry} material={materials['Material.007']} position={[9.132, 0.633, -1.666]} />
      <mesh geometry={nodes.Roca_2.geometry} material={materials['Material.005']} position={[9.126, 0.616, 1.495]} rotation={[0.146, 0.109, -0.06]} scale={1.48} />
      <mesh geometry={nodes.Roca_3.geometry} material={materials['Material.006']} position={[8.532, 0.552, -0.287]} rotation={[2.944, 0.744, -3.051]} scale={1.714} />
      <mesh geometry={nodes.Arbol.geometry} material={materials['Material.009']} position={[-0.555, 3.439, 6.765]} rotation={[0.082, -0.188, 0.015]} scale={[0.778, 0.426, 0.778]} />
      <mesh geometry={nodes.Arbol001.geometry} material={materials['Material.008']} position={[-2.408, 2.97, -0.557]} rotation={[2.941, 1.156, -2.958]} scale={[0.612, 0.335, 0.612]} />
      <mesh geometry={nodes.Arbol002.geometry} material={materials['Material.008']} position={[-0.269, 1.729, -7.701]} rotation={[2.941, 1.156, -2.958]} scale={[0.374, 0.205, 0.374]} />
      <mesh geometry={nodes.Roca_2001.geometry} material={materials['Material.005']} position={[8.196, 0.788, 4.189]} rotation={[0.146, 0.109, -0.06]} scale={1.48} />
      <mesh geometry={nodes.Roca_2002.geometry} material={materials['Material.005']} position={[7.875, 0.439, -4.939]} rotation={[0.146, 0.109, -0.06]} scale={0.946} />
    </group>
  )
}

useGLTF.preload('/Isla.glb')
